pub mod fft_utils;
pub mod beat_detect;
pub mod effects;
pub mod configs;

#[macro_use]
pub mod registry;

use wasm_bindgen::prelude::*;

// Re-export config types for external use
pub use configs::*;

// ChainConfig, process_mono_chain, process_stereo_chain are all
// generated by the effect_registry! macro in registry.rs.
pub use registry::ChainConfig;

/// Process a single mono channel through all enabled effects.
/// Returns processed samples (NOT normalized — caller handles final normalization).
#[wasm_bindgen]
pub fn process_mono(
    samples: &[f32],
    ref_l: &[f32],
    sample_rate: u32,
    config_json: &str,
) -> Vec<f32> {
    let config: ChainConfig = match serde_json::from_str(config_json) {
        Ok(c) => c,
        Err(e) => {
            web_sys::console::error_1(&format!("Config parse error: {}", e).into());
            return samples.to_vec();
        }
    };
    let reference = if ref_l.is_empty() { None } else { Some(ref_l) };
    registry::process_mono_chain(samples, reference, sample_rate, &config)
}

/// Apply stereo effects (e.g., stereo widen) to two pre-processed channels.
/// Returns interleaved stereo output [L,R,L,R,...], normalized to 0.98 peak.
#[wasm_bindgen]
pub fn finalize_stereo(
    out_l: &[f32],
    out_r: &[f32],
    sample_rate: u32,
    config_json: &str,
) -> Vec<f32> {
    let config: ChainConfig = match serde_json::from_str(config_json) {
        Ok(c) => c,
        Err(_) => {
            // Just interleave without stereo effects
            return interleave_and_normalize(out_l, out_r);
        }
    };

    let mut l = out_l.to_vec();
    let mut r = out_r.to_vec();
    registry::process_stereo_chain(&mut l, &mut r, sample_rate, &config);
    interleave_and_normalize(&l, &r)
}

/// Interleave mono to stereo and normalize. Used when no stereo effects needed.
#[wasm_bindgen]
pub fn finalize_mono(out: &[f32]) -> Vec<f32> {
    interleave_and_normalize(out, out)
}

/// Interleave L,R and normalize to 0.98 peak across both channels.
fn interleave_and_normalize(l: &[f32], r: &[f32]) -> Vec<f32> {
    let len = l.len().min(r.len());
    let mut output = Vec::with_capacity(len * 2);
    for i in 0..len {
        output.push(l[i]);
        output.push(r[i]);
    }

    // Final normalization across BOTH channels
    let peak = output.iter().map(|s| s.abs()).fold(0.0f32, f32::max);
    if peak > 1e-8 {
        let ratio = 0.98 / peak;
        for s in output.iter_mut() {
            *s *= ratio;
        }
    }

    output
}

/// Phase 1: Structural effects (beats, warp, ref_warp, seamless_loop).
/// Must process the full buffer. Fast — O(n), no FFT.
#[wasm_bindgen]
pub fn process_structural(
    samples: &[f32],
    ref_l: &[f32],
    sample_rate: u32,
    config_json: &str,
) -> Vec<f32> {
    let config: ChainConfig = match serde_json::from_str(config_json) {
        Ok(c) => c,
        Err(_) => return samples.to_vec(),
    };
    let reference = if ref_l.is_empty() { None } else { Some(ref_l) };
    registry::process_structural(samples, reference, sample_rate, &config)
}

/// Phase 2: FX effects (reshape, reverb, saturate, etc.) on a chunk.
/// Caller should provide overlap at boundaries for STFT effects.
#[wasm_bindgen]
pub fn process_fx_chunk(
    samples: &[f32],
    sample_rate: u32,
    config_json: &str,
) -> Vec<f32> {
    let config: ChainConfig = match serde_json::from_str(config_json) {
        Ok(c) => c,
        Err(_) => return samples.to_vec(),
    };
    registry::process_fx_chunk(samples, sample_rate, &config)
}

/// Legacy all-in-one API (kept for backwards compatibility).
#[wasm_bindgen]
pub fn process_chain(
    input_l: &[f32],
    input_r: &[f32],
    ref_l: &[f32],
    sample_rate: u32,
    config_json: &str,
) -> Vec<f32> {
    let config: ChainConfig = match serde_json::from_str(config_json) {
        Ok(c) => c,
        Err(_) => return input_l.to_vec(),
    };

    let reference = if ref_l.is_empty() { None } else { Some(ref_l) };
    let is_stereo = !input_r.is_empty() && input_r.len() == input_l.len();

    if is_stereo {
        let mut out_l = registry::process_mono_chain(input_l, reference, sample_rate, &config);
        let mut out_r = registry::process_mono_chain(input_r, reference, sample_rate, &config);
        registry::process_stereo_chain(&mut out_l, &mut out_r, sample_rate, &config);
        interleave_and_normalize(&out_l, &out_r)
    } else {
        let out = registry::process_mono_chain(input_l, reference, sample_rate, &config);
        if config.stereo_widen.is_some() {
            let mut out_l = out.clone();
            let mut out_r = out;
            registry::process_stereo_chain(&mut out_l, &mut out_r, sample_rate, &config);
            interleave_and_normalize(&out_l, &out_r)
        } else {
            interleave_and_normalize(&out, &out)
        }
    }
}

/// Get default chain config as JSON
#[wasm_bindgen]
pub fn default_config() -> String {
    let config = ChainConfig::default_config();
    serde_json::to_string(&config).unwrap_or_default()
}
